# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do |options|

    if (options[:versionChange]=='fix')
      gradle(task: 'doFixVersionIncrement')
    elsif (options[:versionChange]=='major')
      gradle(task: 'doMajorVersionIncrement')
    elsif (options[:versionChange]=='major')
      gradle(task: 'doMajorVersionIncrement')
    else
        gradle(task: 'doBuildNumberIncrement')
    end

    gradle(task: 'assemble', build_type: 'release', flavor: 'stage')
    
    crashlytics(
        # keys for organization: VFCU
        api_token: ENV["CRASHLYTICS_API_TOKEN"],
        build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
        groups: "{GROUP}",
        notes: changelog_from_git_commits()
    )

  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
